version: '3.6'
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=employee_management
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
