spring:
  application:
    name: employee-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_management
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: false
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      key-prefix: "employee-management-cache:"
      time-to-live: 180000 # milliseconds - 30 min
    type: redis
    cache-names: employee, emplyoeeList, department, departmentList

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    ignore-missing-migrations: true
    out-of-order: true

server:
  port: 1980